#!/usr/bin/python

import	os
import	sys
import	optparse

def	is_exe( fpath ):
	return os.path.isfile(fpath) and os.access(fpath, os.X_OK)

def	which( program ):
	fpath, fname = os.path.split( program )
	if fpath:
		if is_exe( program ):
			return program
	else:
		for path in os.environ['PATH'].split( os.pathsep ):
			if path == '':
				path = '.'
			fpath = os.path.join( path, program )
			if is_exe(fpath):
				return fpath
	return None

if __name__ == '__main__':
	parser = optparse.OptionParser()
	user = 'root'
	parser.add_option(
		'-u',
		'--user',
		dest='user',
		metavar='user',
		help='whom to write script for; default="%s".' % user,
		default=user
	)
	script = 'funky-stuff'
	parser.add_option(
		'-f',
		'--file',
		dest='script',
		metavar='FILE',
		help='script output; defaults to "%s".' % script,
		default=script
	)
	parser.add_option(
		'-o',
		'--out',
		dest='ofile',
		metavar='FILE',
		help='write to file; defaults to stdout.',
		default=None
	)
	opt, args = parser.parse_args()
	if opt.ofile:
		try:
			out = open( opt.ofile, 'wt' )
		except Exception, e:
			print >>sys.stder, 'Cannot open "%s" for writing.' % opt.ofile
			exit(1)
	else:
		out = sys.stdout
	interactive = os.isatty(0)
	if interactive:
		import	readline
		histfile = os.path.join( os.path.expanduser( '~' ), '.ditwhist' )
		try:
			readline.read_history_file( histfile )
		except IOError:
			pass
		import	atexit
		atexit.register( readline.write_history_file, histfile )
		del	histfile
		readline.parse_and_bind( 'tab: complete' )
		readline.set_history_length( 50 )
	commands = []
	role = '#'
	while True:
		try:
			if interactive:
				s = raw_input( '> ' )
			else:
				s = raw_input()
		except EOFError:
			break
		if s.startswith( '#' ):
			tokens = s[1:].split()
			if len(tokens) > 0:
				tokens[0] = which( tokens[0] )
				commands.append( ' '.join(['#'] + tokens) )
				role = '#'
		elif s.startswith( '$' ):
			commands.append( s )
			role = '$'
		else:
			commands.append( s )
	if interactive:
		print
	print >>out, 'TERM=dumb /bin/script -q %s' % os.path.join(
		os.path.expanduser( '~%s' % opt.user ),
		opt.script
	)
	for command in commands:
		print >>out, '  %s' % command
	print >>out, '  %s exit' % role
	exit(0)
